CREATE TABLE [dbo].[Groups]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(10) NOT NULL UNIQUE CHECK (LEN([Name]) > 0),
	[Rating] INT NOT NULL CHECK ([Rating] BETWEEN 0 AND 5),
	[Year] INT NOT NULL CHECK ([Year] BETWEEN 1 AND 5)
)
